export default {
	
	t1:     'Comment'
	t1x:    'More comments'
	t2fcv:  'User contributing view'
	t2fmv:  'User moderating view'
	t2fv:   'User subscriptions view'
	t2i:    'User information'
	t2ii:   'Current user information'
	t2iix:  'Current user multireddits'
	t2ip:   'User preferences'
	t2ix:   'User multireddits'
	t2iuav: 'User trusted view'
	t2iubv: 'User blocked view'
	t2iucv: 'User contacted view'
	t2iufi: 'User friend notes'
	t2iufv: 'User friended view'
	t2sv:   'User search view'
	t2snv:  'User ranked novelty view'
	t2spv:  'User ranked popularity view'
	t2v:    'User view'
	t3:     'Post'
	t3c:    'Post collection'
	t3dv:   'Post duplicates view'
	t3ldv:  'Live post discussions view'
	t3li:   'Live post information'
	t3lic:  'Live post contributors'
	t3liu:  'Live post update details'
	t3sv:   'Post search view'
	t3w:    'Wiki page'
	t3wdv:  'Wiki page discussions view'
	t3wp:   'Wiki page permissions'
	t3wvv:  'Wiki page versions view'
	t4:     'Message'
	t4c:    'Chat message'
	t4cv:   'Chat messages view'
	t4m:    'Modmail conversation'
	t4miu:  'Modmail conversation author recent actions'
	t4mv:   'Modmail conversations view'
	t4v:    'Messages view'
	t5e:    'Subreddit emotes'
	t5fp:   'Subreddit post flairs'
	t5fu:   'Subreddit user flairs'
	t5g:    'Subreddit widgets'
	t5i:    'Subreddit information'
	t5ir:   'Subreddit rules'
	t5irp:  'Subreddit post requirements'
	t5irpt: 'Subreddit post submission text'
	t5it:   'Subreddit traffic information'
	t5iub:  'Subreddit banned users'
	t5iubw: 'Subreddit wikibanned users'
	t5iuc:  'Subreddit contributors'
	t5iucw: 'Subreddit wiki contributors'
	t5ium:  'Subreddit moderators'
	t5iuu:  'Subreddit muted users'
	t5mev:  'Subreddit edits view'
	t5mlv:  'Subreddit mod log view'
	t5mqv:  'Subreddit mod queue view'
	t5mrv:  'Subreddit reports view'
	t5msv:  'Subreddit spam view'
	t5muv:  'Subreddit mod unactioned view'
	t5sa:   'Subreddit autocomplete search matches'
	t5snv:  'Subreddit ranked novelty view'
	t5spv:  'Subreddit ranked popularity view'
	t5sv:   'Subreddit search view'
	t5v:    'Subreddit view'
	t5w:    'Subreddit wiki pages'
	t5we:   'Subreddit recently edited wiki pages'
	t5xi:   'Multireddit information'
	t5xv:   'Multireddit view'
	t6:     'Award'

}