export keybinds =
    UPVOTE: 'f'
    DOWNVOTE: 'v'
    REPLY: 'r'
    OPEN_POST_IN_NEW_TAB: 'q'
    GO_UP: 'w'
    GO_DOWN: 's'
    GO_LEFT: 'a'
    GO_RIGHT: 'd'
    JUMP_TO_SEARCH_BAR: '/'
    JUMP_TO_POST: 'z'
    JUMP_TO_POSTLIST: 'x'
    JUMP_TO_COMMENTS: 'c'
    DEBUG_INSPECTOR: 'F2'
    DEBUG_STATS: 'F4'
    DEBUG_F7: 'F7'
    DEBUG_F8: 'F8'
    DEBUG_F9: 'F9'
