export Key =
    1: 'Digit1'
    2: 'Digit2'
    3: 'Digit3'
    4: 'Digit4'
    Q: 'KeyQ'
    W: 'KeyW'
    E: 'KeyE'
    A: 'KeyA'
    S: 'KeyS'
    D: 'KeyD'
    Z: 'KeyZ'
    X: 'KeyX'
    C: 'KeyC'
    LShift: 'ShiftLeft'